function rhGoals(){let t=db.weightTracking;if(!Array.isArray(t.milestones)){t.milestones=[330,300,275,250,235].map((weight,i)=>({weight,note:['First milestone','Under 300','Reassess physique','Optional','Optional'][i]}));saveDB()}return t.milestones}
function rhGoalRender(){
const t=db.weightTracking,goals=rhGoals(),entries=[...t.entries].sort((a,b)=>String(a.date).localeCompare(String(b.date))),start=Number(t.plan?.startWeight),current=entries.length?Number(entries[entries.length-1].weight):(start>0?start:null);
const reached=g=>current!==null&&(t.plan?.direction==='gain'?current>=g.weight:current<=g.weight);
const active=goals.find(g=>!reached(g)),summary=document.getElementById('rhGoalSummary'),list=document.getElementById('rhGoalList');
summary.textContent=current===null?'Log a weigh-in in the Weight tab to see progress.':'Current: '+current.toFixed(1)+' lb. '+(active?'Next: '+active.weight+' lb — '+Math.abs(current-active.weight).toFixed(1)+' lb away.':'All milestones reached!');
list.replaceChildren();
goals.forEach((g,i)=>{const row=document.createElement('div');row.className='row between';row.style.cssText='padding:12px 0;border-bottom:1px solid var(--blue-border);gap:8px';const label=document.createElement('div');const title=document.createElement('strong');title.textContent=g.weight+' lb';const note=document.createElement('div');note.className='muted';note.textContent=(g.note||'')+' · '+(reached(g)?'Reached':g===active?'Current goal':'Upcoming');label.append(title,note);const actions=document.createElement('div');actions.className='row';for(const [name,fn] of [['Edit',()=>rhGoalEdit(i)],['Delete',()=>rhGoalDelete(i)]]){const b=document.createElement('button');b.type='button';b.className='secondary small';b.textContent=name;b.onclick=fn;actions.append(b)}row.append(label,actions);list.append(row)});
}
function rhGoalSort(){rhGoals().sort((a,b)=>db.weightTracking.plan?.direction==='gain'?a.weight-b.weight:b.weight-a.weight)}
function rhGoalAdd(e){e.preventDefault();const weight=Number(document.getElementById('rhGoalWeight').value),note=document.getElementById('rhGoalNote').value.trim();if(!(weight>0)||rhGoals().some(g=>g.weight===weight)){alert('Enter a unique positive weight');return}rhGoals().push({weight,note});rhGoalSort();saveDB();e.target.reset();rhGoalRender()}
function rhGoalEdit(i){const g=rhGoals()[i];if(!g)return;const input=prompt('Target weight (lb)',g.weight);if(input===null)return;const weight=Number(input);if(!(weight>0)||rhGoals().some((x,j)=>j!==i&&x.weight===weight)){alert('Enter a unique positive weight');return}const note=prompt('Milestone note',g.note||'');if(note===null)return;g.weight=weight;g.note=note.slice(0,80);rhGoalSort();saveDB();rhGoalRender()}
function rhGoalDelete(i){if(!confirm('Delete this milestone?'))return;rhGoals().splice(i,1);saveDB();rhGoalRender()}
